# Generated by Django 5.0.6 on 2024-06-22 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_flight", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("flights_list", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("location", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="FlightSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("status", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("classname", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="User_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.IntegerField()),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.IntegerField()),
                ("whatsapp", models.IntegerField()),
                ("password", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aiport_start", models.CharField(max_length=30)),
                ("airport_destination", models.CharField(max_length=30)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("status", models.CharField(max_length=30)),
                ("fare", models.ManyToManyField(to="book_flight.flightseat")),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_flight.flights",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flightseat",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="book_flight.seat"
            ),
        ),
        migrations.CreateModel(
            name="BookingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.CharField(max_length=30)),
                ("destination", models.CharField(max_length=30)),
                ("date", models.DateTimeField()),
                ("pnr", models.TextField()),
                ("flight", models.ManyToManyField(to="book_flight.flights")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_flight.user_details",
                    ),
                ),
            ],
        ),
    ]
