# Generated by Django 5.0.6 on 2024-06-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_flight", "0002_airline_airport_flightseat_seat_user_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingdetails",
            name="trip_type",
            field=models.CharField(default="one-way", max_length=10),
        ),
    ]
