# Generated by Django 5.0.6 on 2024-06-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_flight", "0003_bookingdetails_trip_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightseat",
            name="passenger_type",
            field=models.CharField(default="adult", max_length=20),
        ),
        migrations.AlterField(
            model_name="bookingdetails",
            name="trip_type",
            field=models.CharField(max_length=10),
        ),
    ]
