# Generated by Django 5.0.6 on 2024-06-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_flight", "0004_flightseat_passenger_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="passenger_type",
            field=models.CharField(default="adult", max_length=30),
        ),
    ]
