# Generated by Django 5.0.6 on 2024-06-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_flight", "0005_seat_passenger_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="seat", name="passenger_type",),
    ]
