# Generated by Django 5.0.6 on 2024-07-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HolidayPackages",
            fields=[
                (
                    "holiday_package_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("holiday_package_type", models.CharField(max_length=30)),
                ("destination", models.TextField()),
                ("adult_price", models.FloatField()),
                ("all_inclusive", models.BooleanField()),
                ("children_price", models.FloatField()),
            ],
        ),
    ]
